#ifndef DEFAULT_SETTINGS_HPP
#define DEFAULT_SETTINGS_HPP

#define DEFAULT_SERVER_PORT 4242
#define DEFAULT_BUFLEN 4096
#define DEFAULT_SERVER_IP "127.0.0.1"
#define MAX_CLIENTS 42
#define DEFAULT_LISTEN_QUEUE 5
#define DEFAULT_CONFIG_FILE "./config/default.21ws"

#endif
